config/routes.rb
Todo::Application.routes.draw do
  resources :projetos do
    resources :tarefas, :except => [:show] do
      member do
        post :finalizar
      end
    end
    member do
      get :colaboradores
      post :adicionar_coordenador
    end
  end

  resources :colaboradores

  root :to => 'projetos#index'
end

app/models/colaborador.rb
#encoding: UTF-8
class Colaborador < ActiveRecord::Base
  has_many :colaboradores_projetos
  has_many :projetos, through: :colaboradores_projetos

  validates :matricula, :presence => {:message => "A matricula deve ser preenchido."}, :uniqueness => {:message => "Já existe um colaborador com essa matricula."}
  validates :nome,      :presence => {:message => "O nome deve ser preenchido."}
  validates :cargo,     :presence => {:message => "O cargo deve ser preenchido."}

  def nome_completo
    matricula.to_s + " " + nome
  end

end

app/models/colaborador_projeto.rb
class ColaboradorProjeto < ActiveRecord::Base
  belongs_to :colaborador
  belongs_to :projeto

  validates :colaborador_id, :presence => {:message => "Deve possuir o id de um colaborador"}
  validates :projeto_id, :presence => {:message => "Deve possuir o id de um projeto"}
end

app/models/projeto.rb
#encoding: utf-8
class Projeto < ActiveRecord::Base
  has_many :tarefas
  has_many :colaboradores_projetos
  has_many :colaboradores, through: :colaboradores_projetos
  validates_presence_of :nome, :message => 'deve ser preenchido'
  validates_size_of :nome, :minimum => 3
  validate :letra_maiuscula_projeto
  validates :data_inicio, :timeliness => {:on_or_after => Date.today}, :presence => {:message => "Deve ser preenchido"}

  private
    def letra_maiuscula_projeto
      errors.add(:nome, "Primeira letra do nome deve ser maiuscula") unless nome =~ /^[A-Z]/
    end
end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
  belongs_to :projeto
  belongs_to :colaborador

  validates_presence_of :descricao, {:message => "Deve ser preenchido"}
  validates_presence_of :colaborador_id, {:message => "Deve ser escolhido"}
  validates_size_of :descricao, :minimum => 3
  validates :projeto_id, :presence => {:message => "Deve ser preenchido"}
  
  scope :do_projeto, lambda{|projeto_id| Tarefa.where(:projeto_id => projeto_id)}

  def concluir!
    update_attribute(:data_finalizacao,Date.today)
  end

  def concluida?
    !data_finalizacao.nil?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colaboradores_controller.rb
class ColaboradoresController < ApplicationController
  # GET /colaboradores
  # GET /colaboradores.json
  def index
    @colaboradores = Colaborador.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colaboradores }
    end
  end

  # GET /colaboradores/1
  # GET /colaboradores/1.json
  def show
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradores/new
  # GET /colaboradores/new.json
  def new
    @colaborador = Colaborador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradores/1/edit
  def edit
    @colaborador = Colaborador.find(params[:id])
  end

  # POST /colaboradores
  # POST /colaboradores.json
  def create
    @colaborador = Colaborador.new(params[:colaborador])

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully created.' }
        format.json { render json: @colaborador, status: :created, location: @colaborador }
      else
        format.html { render action: "new" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colaboradores/1
  # PUT /colaboradores/1.json
  def update
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      if @colaborador.update_attributes(params[:colaborador])
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradores/1
  # DELETE /colaboradores/1.json
  def destroy
    @colaborador = Colaborador.find(params[:id])
    @colaborador.destroy

    respond_to do |format|
      format.html { redirect_to colaboradores_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projetos_controller.rb
#encoding: utf-8
class ProjetosController < ApplicationController
  def index
    @projetos = Projeto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projetos }
    end
  end

  def show
    @projeto = Projeto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projeto }
    end
  end

  def new
    @projeto = Projeto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projeto }
    end
  end

  def edit
    @projeto = Projeto.find(params[:id])
  end

  def create
    @projeto = Projeto.new(params[:projeto])

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to :action => :index, notice: 'Projeto criado com sucesso.' }
        format.json { render json: @projeto, status: :created, location: @projeto }
      else
        format.html { render action: "new" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @projeto = Projeto.find(params[:id])

    respond_to do |format|
      if @projeto.update_attributes(params[:projeto])
        format.html { redirect_to :action => :index, notice: 'Projeto atualizado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @projeto = Projeto.find(params[:id])
    @projeto.destroy

    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :ok }
    end
  end

  def colaboradores
    @projeto = Projeto.find(params[:id])
    @colaboradores = @projeto.colaboradores
  end

  def adicionar_coordenador
    @projeto = Projeto.find(params[:id])
    params_cp = {:colaborador_id => params[:colaborador_id], :projeto_id => params[:projeto_id]}
    @colaborador_projeto = ColaboradorProjeto.new(params_cp)
    if @colaborador_projeto.save
      redirect_to colaboradores_projeto_path(@projeto), :notice => "Colaborador cadastrado com sucesso"
    else
      redirect_to colaboradores_projeto_path(@projeto), :error => "Não foi possível cadastrar esse colaborador. Erros: #{@colaborador_projeto.errors}"
    end
  end
end

app/controllers/tarefas_controller.rb
# encoding: UTF-8
class TarefasController < ApplicationController

  def new
    @tarefa = Tarefa.new
    render 'novo'
  end

  def create
    @tarefa = Tarefa.new params[:tarefa]
    if !@tarefa.save
      flash[:error] = "Existem erros que impedem a inclusão"
      render :novo
    else
      redirect_to :action => :index, notice: "Tarefa #{params[:id]} criada com sucesso"
    end
  end

  def index
    @projeto = Projeto.find params[:projeto_id]
    @tarefas = @projeto.tarefas
  end

  def edit
    @tarefa = Tarefa.find params[:id]
  end

  def update
    @tarefa = Tarefa.find params[:id]
    @tarefa.update_attributes params[:tarefa]
    if @tarefa.save
      flash[:notice] = "Tarefa #{params[:id]} atualizada com sucesso"
      redirect_to :action => :index
    else
      flash[:error] = "Existem erros que impedem a atualizacao"
      render :action => :edit
    end
  end

  def destroy
    Tarefa.destroy params[:id]
    flash[:notice] = "Tarefa #{params[:id]} removida com sucesso"
    redirect_to :action => :index
  end

  def finalizar
    Tarefa.find(params[:id]).concluir!
    flash[:notice] = "Tarefa #{params[:id]} finalizada"
    redirect_to :action => :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaboradores_helper.rb
module ColaboradoresHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper

end

app/views/colaboradores/_form.html.erb
<%= form_for(@colaborador) do |f| %>
  <% if @colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% @colaborador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :matricula %>
    <%= f.text_field :matricula %>
  </p>

  <p>
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </p>

  <p>
    <%= f.label :cargo %>
    <%= f.text_field :cargo %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colaboradores/edit.html.erb
<h1>Editing colaborador</h1>

<%= render 'form' %>

<%= link_to 'Show', @colaborador %> |
<%= link_to 'Back', colaboradores_path %>

app/views/colaboradores/index.html.erb
<h1>Colaboradores</h1>

<table>
  <tr>
    <th>Matrícula</th>
    <th>Nome</th>
    <th>Cargo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colaboradores.each do |colaborador| %>
  <tr>
    <td><%= colaborador.matricula %></td>
    <td><%= colaborador.nome %></td>
    <td><%= colaborador.cargo %></td>
    <td><%= link_to 'Editar', edit_colaborador_path(colaborador) %></td>
    <td><%= link_to 'Deletar Colaborador', colaborador, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar Colaborador', new_colaborador_path %>

app/views/colaboradores/new.html.erb
<h1>New colaborador</h1>

<%= render 'form' %>

<%= link_to 'Back', colaboradores_path %>

app/views/colaboradores/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_colaborador_path(@colaborador) %> |
<%= link_to 'Back', colaboradores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo - Innvent Bootcamp</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= yield :js %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<%= render partial: "shared/menu" %>

    <div class="container">
      <% if flash[:notice] %>
        <p style="color:green;"><%= flash[:notice]%></p>
      <% end %>
      <% if flash[:error] %>
        <p style="color:red;"><%= flash[:error]%></p>
      <% end %>

	    <%= yield %>

      <footer>
        <hr>
        <p>© <a href="http://www.innvent.com.br/" target="_blank">Innvent</a> <%= DateTime.now.year %></p>
      </footer>
    </div>    
  </body>
  <script type="text/javascript">
    $(".modal_form").dialog({
      autoOpen: false,
      modal: true
    });

    $(".modal_button").click(function(){
      $(".modal_form").dialog("open");
    });
  </script>
</html>

app/views/projetos/_form.html.erb
<%= render :partial => 'shared/mensagem_erro', :object => @projeto%>
<%= form_for(@projeto) do |f| %>
   <p>
     <%= f.label 'Nome' %>
	 	 <%= f.text_field :nome%>
   </p>
   <p>
     <%= f.label 'Data de entrega' %>
	 	 <%= f.date_select :data_entrega, :start_year => Time.now.year, :order => [:day, :month, :year], :use_month_numbers => true %>
   </p>
   <p>
     <%= f.label 'Responsavel' %>
	 	 <%= f.text_field :responsavel%>
   </p>
  <div class="actions">
    <%= f.submit "Salvar Informações" %>
  </div>
<% end %>

app/views/projetos/colaboradores.html.erb
<h2>Colaboradores do projeto <%= @projeto.nome %></h2>

<% if @colaboradores.any? %>
  <table>
    <thead>
      <tr>
        <td>Matrícula</td>
        <td>Nome</td>
        <td>Cargo</td>
      </tr>
    </thead>
    <tbody>
    <% @colaboradores.each do |colaborador| %>
      <tr>
        <td><%= colaborador.matricula %></td>
        <td><%= colaborador.nome %></td>
        <td><%= colaborador.cargo %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existe nenhum colaborador cadastrado nesse projeto.</p>
<% end %>

<span class="modal_button">Adicionar Colaborador</span>

<div class="modal_form" title="Adicionar Colaborador">
  <%= form_tag adicionar_coordenador_projeto_path(@projeto) do %>
    <%= hidden_field_tag :projeto_id, @projeto.id %>
    <%= label_tag :colaborador_id, "Colaborador:" %>
    <%= select_tag :colaborador_id, options_from_collection_for_select(Colaborador.all, "id", "nome_completo") %>
    <%= submit_tag "Salvar" %>
  <% end %>
</div>

app/views/projetos/edit.html.erb
<h1>Edição de projetos</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @projeto %> |
<%= link_to 'Voltar', projetos_path %>

app/views/projetos/index.html.erb
<h2>Projetos</h2>

<table class="table">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Responsavel</th>
    <th>Data de Entrega</th>	  
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

<% @projetos.each do |projeto| %>
  <tr>
	<td><%=projeto.nome%></td>
	<td><%=projeto.responsavel%></td>
	<td><%=projeto.data_entrega%></td>
    <td><%= link_to 'Altera', edit_projeto_path(projeto) %></td>
    <td><%= link_to 'Remove', projeto,
		 	confirm: 'Are you sure?' %>
	</td>
  </tr>
<% end %>
</table>

<br />
<%= link_to('Novo Projeto', new_projeto_path) %>

app/views/projetos/new.html.erb
<h1>Novo Projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projetos_path %>

app/views/projetos/show.html.erb
<div>
	<h2><%= @projeto.nome %></h2>
	<dl>
	  <dt><%= label_tag 'Responsavel:'%></dt>
  	  <dd><%= @projeto.responsavel %></dd>
	  <dt><%= label_tag 'Entrega prevista para:'%></dt>
	  <dd><%= @projeto.data_entrega %></dd>
    </dl>	  
</div>
<h3> Tarefas </h3>

<%= render :partial => 'tarefas/lista_tarefa', :object => @projeto.tarefas %>

<br/>
<%= link_to 'Editar', edit_projeto_path(@projeto) %> |
<%= link_to 'voltar', projetos_path %>

app/views/shared/_linha_erro.html.erb
<p><%= linha_erro %></p>

app/views/shared/_mensagem_erro.html.erb
<div class="form-error">
	<%= render :partial => 'shared/linha_erro', :collection => mensagem_erro.errors.full_messages %>
</div>

app/views/shared/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="<%= root_path %>">TODO - Innvent Bootcamp</a>
      <div class="nav-collapse collapse">
        <ul class="nav">          
          <li class="dropdown" id="menu_colaboradores">
            <a href="#menu_colaboradores" class="dropdown-toggle" data-toggle="dropdown">Colaboradores <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Gerenciar Coordenadores", colaboradores_path %></li>
            </ul>
          </li>
          <li class="dropdown" id="menu_projetos">
            <a href="#menu_projetos" class="dropdown-toggle" data-toggle="dropdown">Projetos <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="<%= projetos_path %>">Cadastro de Projetos</a></li>              
              <li class="divider"></li>
              <% Projeto.all.each do |projeto| %>
                <li class="nav-header"><%= projeto.nome %></li>
                <li><a href="<%= projeto_tarefas_path(projeto) %>">Tarefas</a></li>
                <li><a href="<%= colaboradores_projeto_path(projeto) %>">Colaboradores do Projeto</a></li>
                <li><a href="<%= edit_projeto_path(projeto) %>">Editar Projeto</a></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/tarefas/_form.html.erb
<div class="modal_form" title="Criar Tarefa">
<%= form_for :tarefa, :html => {:id =>'form_projeto_tarefa'} do |f| %>
<%= f.hidden_field :projeto_id, :value => @projeto.id %>
	Responsavel:
  <p><%= f.text_field :responsavel %></p>
	Descricao:
	<p><%= f.text_area :descricao %></p>
	<%= f.submit %>
<% end %>
</div>

app/views/tarefas/_lista_tarefa.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Descricao</th>
			<th>Responsavel</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<% lista_tarefa.each do |tarefa| %>
		<tr id="tarefa_<%=tarefa.id%>">
      <% if tarefa.concluida? %>
        <td class="tarefa_concluida"><%= tarefa.descricao %></td>
      <% else %>
        <td><%= tarefa.descricao %></td>
      <% end %>
			<td><%= tarefa.responsavel %></td>
			<td><%= link_to 'Alterar', edit_projeto_tarefa_path(tarefa.projeto, tarefa) %></td>
			<td><%= button_to 'Finalizar', finalizar_projeto_tarefa_path(tarefa.projeto, tarefa) unless tarefa.concluida? %></td>
			<td>
				<%= link_to 'Remover', projeto_tarefa_path(tarefa.projeto,tarefa),
				  	:method => :delete,
						:class => 'remove-tarefa', 'data-elemento_id' => "tarefa_#{tarefa.id}" %>
			</td>
		</tr>
	<%end%>
</table>

<%=content_for :js do%>
	<%= javascript_include_tag "tarefas" %>
<%end%>

app/views/tarefas/create.html.erb
<h4>Tarefa criada com sucesso.</h4>

app/views/tarefas/create.js.erb
<%= render :partial => 'tarefas/lista_tarefa', :object => @tarefa.projeto.tarefas %>

app/views/tarefas/edit.html.erb
<h3> Altera Tarefa: <%=@tarefa.id%> </h3>

<%= render :partial => 'shared/mensagem_erro', :object => @tarefa %>
<%= render :partial => 'form', :locals => {:tarefa => @tarefa} %>

app/views/tarefas/index.html.erb
<h2>Lista de Tarefas</h2>

<div id="resultado">
	<%= render :partial => 'lista_tarefa', :object => @tarefas %>
</div>

<%#= link_to 'Nova Tarefa', new_projeto_tarefa_path(@projeto), :id => 'cria_nova_tarefa' %>

<span class="modal_button">Criar Tarefa</span>

<%= render "form" %>

app/views/tarefas/novo.html.erb
<h3> Nova Tarefa </h3>

<%= render :partial => 'shared/mensagem_erro', :object => @tarefa %>
<%= render :partial => 'form', :locals => {:tarefa => @tarefa} %>